apiVersion: v1
kind: Pod
metadata:
  name: best-app
  labels:
    app: best-app
spec:
  containers:
  - name: best-app
    image: manavrajvanshinx/best-app:latest
    resources:
      limits:
        memory: 512Mi
        cpu: "1"
    env:
    - name: DBHOST
      value: mazin-db-mssqltest-svc
    - name: DBPORT
      value: '80'
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-secret-pg-si
          key: password
    ports:
    - containerPort: 3000
  initContainers:
  - name: init-db
    image: busybox:1.28
    command: ['sh', '-c', "until nslookup mazin-db-mssqltest-svc.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for database service; sleep 2; done"]
